services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=cacotalk
      - POSTGRES_USER=jux
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: