spring.application.name=cacotalk

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.data.redis.host=${REDIS_HOST}

# sliding expiry
app.auth.session.ttl=7d
app.auth.session.cookie-secure=true

app.frontend-origin=${FRONTEND_ORIGIN}

app.message-encryption-key=${MESSAGE_ENCRYPTION_KEY}

spring.profiles.active=${SPRING_PROFILES_ACTIVE}