spring.application.name=cacotalk

spring.datasource.url=jdbc:postgresql://localhost:5432/cacotalk
spring.datasource.username=jux
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

# sliding expiry
app.auth.session.ttl=7d
app.auth.session.cookie-secure=true

spring.profiles.active=dev